spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

  application:
    name: event-ticketing-backend

  # PostgreSQL (Supabase) - Main Database
  datasource:
    url: URL            # Replace with your real Url
    username: USERNAME  # Replace with your real Username
    password: PASSWORD  # Replace with your real password
    driver-class-name: org.postgresql.Driver

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    max-lifetime: 1800000
    connection-timeout: 60000
    idle-timeout: 600000
    connection-test-query: "SELECT 1"

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true


  data:
    redis:
      url: URL                                # Replace with your real Url
      timeout: 30s
      repositories:
        enabled: false



  # RabbitMQ (CloudAMQP) - Message Queue
  rabbitmq:
    addresses: URL                               # Replace with your real Url
    connection-timeout: 60000ms
    requested-heartbeat: 60s

  # Email Configuration (we'll add Gmail SMTP later)
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc@gmail.com                         # Replace with your Gmail
    password: Unique 16 digit Gmail App Password    # Use Gmail App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: 8081

# JWT Configuration (for authentication)
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours

# Logging
logging:
  level:
    com.eventtickets: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"


google:
  maps:
    api-key: xxxxxxxxxxxx      # Replace with your real Google Api-Key


razorpay:
  key-id: KEY-ID                   # Replace with your real Kei -id
  key-secret: XXXXXXXX             # Replace with your real Key-Secret
  #webhook-secret: YOUR_WEBHOOK_SECRET # We'll generate this later


cache:
  ttl:
    events: 3600  # 1 hour in seconds
    users: 1800   # 30 minutes in seconds
